CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT
);
CREATE TABLE credentials(
user_id INTEGER UNIQUE,
password TEXT,
email TEXT UNIQUE,
FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE CASCADE
);
CREATE TABLE friends(
user_id INTEGER,
friend_id INTEGER,
FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE CASCADE,
FOREIGN KEY(friend_id) REFERENCES users(id)
ON DELETE CASCADE
);
CREATE TABLE enemies(
user_id INTEGER,
enemy_id INTEGER,
FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE CASCADE,
FOREIGN KEY(enemy_id) REFERENCES users(id)
ON DELETE CASCADE
);
CREATE TABLE friend_posts(
user_id INTEGER,
post TEXT, title TEXT,
time TIMESTAMP,
FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE CASCADE
);
CREATE TABLE enemy_posts(
user_id INTEGER,
post TEXT, title TEXT,
time TIMESTAMP,
FOREIGN KEY(user_id) REFERENCES users(id)
ON DELETE CASCADE
);
